"""Markdown reporter for human-readable abuse analysis reports."""

from __future__ import annotations

from pathlib import Path

from cad.scoring.models import AbuseReport, Severity


class MarkdownReporter:
    """Generates Markdown reports for security teams and leadership.

    Produces a structured report with:
    - Executive summary with threat level
    - Score breakdown by category
    - Top threats with evidence
    - Actionable recommendations
    """

    def render(self, report: AbuseReport) -> str:
        """Render the report as a Markdown string."""
        lines: list[str] = []

        # Header
        lines.append("# Commerce Abuse Defense -- Abuse Report")
        lines.append("")
        lines.append(f"**Report ID:** {report.report_id}")
        lines.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        if report.period_start and report.period_end:
            lines.append(
                f"**Period:** {report.period_start.strftime('%Y-%m-%d %H:%M')} "
                f"to {report.period_end.strftime('%Y-%m-%d %H:%M')}"
            )
        if report.sources:
            lines.append(f"**Sources:** {', '.join(report.sources)}")
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        threat_label = report.score.threat_level.value.upper()
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| **Abuse Score** | **{report.score.total_score}/100** |")
        lines.append(f"| **Threat Level** | **{threat_label}** |")
        lines.append(f"| **Events Analyzed** | {report.score.total_events_analyzed} |")
        lines.append(f"| **Detections** | {report.score.total_detections} |")
        lines.append("")

        # Score Breakdown
        lines.append("## Score Breakdown")
        lines.append("")
        lines.append("| Category | Raw Score | Weight | Weighted | Detections |")
        lines.append("|----------|----------|--------|----------|------------|")
        for cat in sorted(report.score.categories, key=lambda c: c.weighted_score, reverse=True):
            lines.append(
                f"| {cat.category.replace('_', ' ').title()} "
                f"| {cat.score} | {cat.weight:.0%} "
                f"| {cat.weighted_score} | {len(cat.detections)} |"
            )
        lines.append("")

        # Top Threats
        if report.top_threats:
            lines.append("## Top Threats")
            lines.append("")
            for i, threat in enumerate(report.top_threats, 1):
                lines.append(f"{i}. {threat}")
            lines.append("")

        # Detection Details
        if report.detections:
            lines.append("## Detection Details")
            lines.append("")
            for detection in sorted(
                report.detections,
                key=lambda d: list(Severity).index(d.severity),
                reverse=True,
            ):
                severity_tag = detection.severity.value.upper()
                lines.append(f"### [{severity_tag}] {detection.rule_name} ({detection.rule_id})")
                lines.append("")
                lines.append(f"**Confidence:** {detection.confidence:.0%}")
                lines.append("")
                lines.append(detection.description)
                lines.append("")
                if detection.evidence:
                    lines.append("**Evidence:**")
                    for ev in detection.evidence:
                        lines.append(f"- {ev}")
                    lines.append("")

        # Recommendations
        if report.recommendations:
            lines.append("## Recommendations")
            lines.append("")
            for rec in report.recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by Commerce Abuse Defense (CAD) v0.1.0*")
        lines.append("")

        return "\n".join(lines)

    def write(self, report: AbuseReport, output_path: str | Path) -> None:
        """Write the Markdown report to a file."""
        content = self.render(report)
        Path(output_path).write_text(content, encoding="utf-8")
